### ISSUE TITLE
Error while running `sudo rpm-ostree rebase --experimental ostree-unverified-registry:docker.io/kevydotvinu/oibl-ostree`

### ISSUE THREAD

**Issue by k37y** [k37y/ocp-ipi-baremetal-lab#5]
![image](https://user-images.githubusercontent.com/31133195/211872396-95033c42-8cac-4082-8144-f2c04dbe8c76.png)

**Comment by kevydotvinu** [comment]
The current ostree image is built on top of fcos 36. Hence, use the Fedora CoreOS 36 ISO image as a workaround for the issue.
